#### pandas içe aktarma

In [ ]:
import pandas as pd

#### pandas veri yapıları - Seriler -

In [ ]:
pandas_veri= pd.Series([1,2,3,4])
print("pandas_veri \n",pandas_veri)
print("-"*30)
print("ilk veri",pandas_veri[0])

pandas_veri
 0    1
1    2
2    3
3    4
dtype: int64
------------------------------
ilk veri 1

In [ ]:
pandas_etiketli_veri=pd.Series([1,2,3,4],["A","B","C","D"])
print("etiketli_veri\n",pandas_etiketli_veri)
print("-"*30)
print("b satırı",pandas_etiketli_veri["B"])

etiketli_veri
 A    1
B    2
C    3
D    4
dtype: int64
------------------------------
b satırı 2

In [ ]:
import numpy as np 
sayılar=np.arange(10,20,2)
print(sayılar[0])
pandas_sayılar=pd.Series(sayılar)
print(pandas_sayılar[0])
etiketler=["A","B","C","D","E"]
pandas_etiketli_sayılar=pd.Series(sayılar,etiketler)
print(pandas_etiketli_sayılar["B"])

10
10
12

In [ ]:
etiketler=["AB","EU","GB","JP","USA"]
puan1=[10,20,60,40,30]
puan2=[60,30,50,80,62]
veri1=pd.Series(data=puan1,index=etiketler)
veri2=pd.Series(data=puan2,index=etiketler)
print(veri1,veri2)

print("toplam=",veri1+veri2)

AB     10
EU     20
GB     60
JP     40
USA    30
dtype: int64 AB     60
EU     30
GB     50
JP     80
USA    62
dtype: int64
toplam= AB      70
EU      50
GB     110
JP     120
USA     92
dtype: int64

#### pandas veri yapıları - Veri çerçeveleri -

In [ ]:
sayılar=np.arange(0,20).reshape(4,5)
print(sayılar)
print("-"*30) # araya çizgi ekleme
sütunlar=["A","B","C","D","E"]
satırlar=["AB","EU","GB","JP"]
tablo=pd.DataFrame(sayılar,index=satırlar,columns=sütunlar)
print(tablo)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
------------------------------
     A   B   C   D   E
AB   0   1   2   3   4
EU   5   6   7   8   9
GB  10  11  12  13  14
JP  15  16  17  18  19

#### seçim-ekleme-çıkarma işlemleri

In [ ]:
# A sütünundaki verileri gösterme
tablo["A"]

AB     0
EU     5
GB    10
JP    15
Name: A, dtype: int64

In [ ]:
# A ve B sütünundaki verileri gösterme
tablo[["A","B"]]

     A   B
AB   0   1
EU   5   6
GB  10  11
JP  15  16

In [ ]:
# AB satırındaki verileri gösterme
tablo.loc["AB"]

A    0
B    1
C    2
D    3
E    4
Name: AB, dtype: int64

In [ ]:
tablo.iloc[0]

A    0
B    1
C    2
D    3
E    4
Name: AB, dtype: int64

In [ ]:
# AB,EU satır ve C,D sütünlarının kesişimini seçmek 
tablo.loc[["AB","EU"],["C","D"]]

    C  D
AB  2  3
EU  7  8

#### koşullu seçim

 tabloda 2 den büyük sayıları seçmek
 tabloda 2 den büyük ve 10 dan küçük sayıları seçmek

In [ ]:
tablo[tablo>2]

       A     B     C   D   E
AB   NaN   NaN   NaN   3   4
EU   5.0   6.0   7.0   8   9
GB  10.0  11.0  12.0  13  14
JP  15.0  16.0  17.0  18  19

In [ ]:
tablo[(tablo>2) & (tablo<10)]

      A    B    C    D    E
AB  NaN  NaN  NaN  3.0  4.0
EU  5.0  6.0  7.0  8.0  9.0
GB  NaN  NaN  NaN  NaN  NaN
JP  NaN  NaN  NaN  NaN  NaN

# bazı matematiksel işlemler

In [ ]:
print(" Tablodaki en büyük değerler   \n",tablo.max())
print(" Tablodaki ortalama değerler   \n",tablo.mean())
print("C sutünundaki en büyük değer     ",tablo["C"].max())
print("C sutünundaki ortalama değer     ",tablo["C"].mean())
print("C sutünundaki en küçük değer     ",tablo["C"].min())
print("C sutünundaki değerlerin toplamı ",tablo["C"].sum())

 Tablodaki en büyük değerler
 A    10
B    11
C    12
D    13
E    14
dtype: int64
 Tablodaki ortalama değerler
 A    5.0
B    6.0
C    7.0
D    8.0
E    9.0
dtype: float64
C sutünundaki en büyük değer      12
C sutünundaki ortalama değer      7.0
C sutünundaki en küçük değer      2
C sutünundaki değerlerin toplamı  21

In [ ]:
tablo.loc[["AB","EU"],["C","D"]].sum()

C     9
D    11
dtype: int64

In [ ]:
# veri çerçevesine yeni sütun ekleme
print("öncesi \n",tablo)
print("-"*30)
tablo["toplam"]=tablo["A"]+tablo["B"]+tablo["C"]+tablo["D"]+tablo["E"]
print("sonrası \n",tablo)

öncesi
      A   B   C   D   E
AB   0   1   2   3   4
EU   5   6   7   8   9
GB  10  11  12  13  14
JP  15  16  17  18  19
------------------------------
sonrası
      A   B   C   D   E  toplam
AB   0   1   2   3   4      10
EU   5   6   7   8   9      35
GB  10  11  12  13  14      60
JP  15  16  17  18  19      85

In [ ]:
# veri çerçevesinden sütun çıkarma
print("öncesi \n",tablo)
print("-"*30)
tablo.drop("toplam",axis=1,inplace=True)
print("sonrası \n",tablo)

öncesi
      A   B   C   D   E  toplam
AB   0   1   2   3   4      10
EU   5   6   7   8   9      35
GB  10  11  12  13  14      60
JP  15  16  17  18  19      85
------------------------------
sonrası
      A   B   C   D   E
AB   0   1   2   3   4
EU   5   6   7   8   9
GB  10  11  12  13  14
JP  15  16  17  18  19

In [ ]:
# veri çerçevesinden satır çıkarma
print("öncesi \n",tablo)
print("-"*30)
tablo.drop("JP",axis=0,inplace=True)
print("sonrası \n",tablo)

öncesi
      A   B   C   D   E
AB   0   1   2   3   4
EU   5   6   7   8   9
GB  10  11  12  13  14
JP  15  16  17  18  19
------------------------------
sonrası
      A   B   C   D   E
AB   0   1   2   3   4
EU   5   6   7   8   9
GB  10  11  12  13  14

#### dosyalarla çalışmak

In [1]:
import pandas as pd
import numpy as np
dosya=pd.read_csv("/content/ornek.csv")
dosya

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
#satır toplamlarını toplam isminde eklemek
dosya["toplam"]=dosya.sum(axis=1)
dosya

    a   b   c   d  toplam
0   0   1   2   3      12
1   4   5   6   7      44
2   8   9  10  11      76
3  12  13  14  15     108

In [6]:
dosya.to_csv("/content/ornek2.csv")
yeni_dosya=pd.read_csv("/content/ornek2.csv")
yeni_dosya

   Unnamed: 0   a   b   c   d  toplam
0           0   0   1   2   3      12
1           1   4   5   6   7      44
2           2   8   9  10  11      76
3           3  12  13  14  15     108

In [7]:
notlar=pd.read_excel("/content/sınav.xlsx")
notlar

     isim  1. yazılı  2. yazılı
0     ali         50         85
1    veli         55         80
2    ayşe         60         75
3  ceylan         65         70
4    umut         70         65
5   selim         75         60
6  zeynep         80         55
7   bahar         85         50

In [8]:
notlar["ortalama"]=(notlar["1. yazılı"]+notlar["2. yazılı"])/2
notlar

     isim  1. yazılı  2. yazılı  ortalama
0     ali         50         85      67.5
1    veli         55         80      67.5
2    ayşe         60         75      67.5
3  ceylan         65         70      67.5
4    umut         70         65      67.5
5   selim         75         60      67.5
6  zeynep         80         55      67.5
7   bahar         85         50      67.5

In [9]:
notlar.to_excel("/content/sınav2.xlsx")

In [10]:
sonuc=pd.read_excel("/content/sınav2.xlsx")
sonuc.head(5)

   Unnamed: 0    isim  1. yazılı  2. yazılı  ortalama
0           0     ali         50         85      67.5
1           1    veli         55         80      67.5
2           2    ayşe         60         75      67.5
3           3  ceylan         65         70      67.5
4           4    umut         70         65      67.5

In [11]:
sonuc.tail(5) #son 5 veri

   Unnamed: 0    isim  1. yazılı  2. yazılı  ortalama
3           3  ceylan         65         70      67.5
4           4    umut         70         65      67.5
5           5   selim         75         60      67.5
6           6  zeynep         80         55      67.5
7           7   bahar         85         50      67.5

In [12]:
sonuc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8 non-null      int64
 1   isim        8 non-null      object
 2   1. yazılı   8 non-null      int64
 3   2. yazılı   8 non-null      int64
 4   ortalama    8 non-null      float64
dtypes: float64(1), int64(3), object(1)
memory usage: 448.0+ bytes

In [13]:
print("satır etikeleri",sonuc.columns)

satır etikeleri Index(['Unnamed: 0', 'isim', '1. yazılı', '2. yazılı', 'ortalama'], dtype='object')

In [14]:
sonuc.describe()

       Unnamed: 0  1. yazılı  2. yazılı  ortalama
count     8.00000   8.000000   8.000000       8.0
mean      3.50000  67.500000  67.500000      67.5
std       2.44949  12.247449  12.247449       0.0
min       0.00000  50.000000  50.000000      67.5
25%       1.75000  58.750000  58.750000      67.5
50%       3.50000  67.500000  67.500000      67.5
75%       5.25000  76.250000  76.250000      67.5
max       7.00000  85.000000  85.000000      67.5